blank_issues_enabled: true
contact_links:
  - name: Questions and support
    url: https://github.com/Sweekriti91/repo-health-checker/discussions
    about: Please ask and answer questions in Discussions.
